Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -54,4 +54,17 @@ jobs:
             pqsdktools\tools\PQTest.exe set-credential --extension "bin\AnyCPU\Debug\s.mez" --queryFile "ADHPowerQuery.query.pq" --prettyPrint < cred.json
             echo Running unit tests
             pqsdktools\tools\PQTest.exe run-test --extension "bin\AnyCPU\Debug\s.mez" --queryFile "ADHPowerQuery.query.pq" --prettyPrint
-            
+        displayName: Run Tests
+        
+      - task: PowerShell@2
+        inputs:
+          script: |
+            $Results = Get-Content -Path results.json | ConvertFrom-Json
+            if ($Results.Output[0].Details -eq "100% success rate") {
+                echo "Success"
+                exit 0
+            } else {
+                echo "Failure"
+                exit 1
+            }
+        displayName: Check Results
